packages:
  - '!**/.next/**'
  - '!**/dist/**'

  - 'apps/core'
  - 'apps/explorer'
  - 'apps/icons'
  - 'apps/ui'

  - 'sdk/bcs'
  - 'sdk/build-scripts'
  - 'sdk/dapp-kit'
  - 'sdk/kiosk'
  - 'sdk/typescript'
  - 'sdk/wallet-standard'
  - 'sdk/zksend'

  - '!sdk/typescript/bcs'
  - '!sdk/typescript/client'
  - '!sdk/typescript/cryptography'
  - '!sdk/typescript/faucet'
  - '!sdk/typescript/graphql'
  - '!sdk/typescript/multisig'
  - '!sdk/typescript/transactions'
  - '!sdk/typescript/utils'
  - '!sdk/typescript/verify'
  - '!sdk/typescript/zklogin'
